name: C CI

on:
  push:
  pull_request:

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc make clang-format

      - name: Check formatting
        run: make check-format

      - name: Run tests
        run: make test
